CREATE TABLE IF NOT EXISTS ESTUDANTES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    NUMERO_ESTUDANTE INT UNSIGNED NOT NULL,
    CURSO VARCHAR(255) NOT NULL,
    CONTACTO VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    LIVROS INT NOT NULL DEFAULT 0,
    PASS VARCHAR(255) NOT NULL DEFAULT '12345'
);

CREATE TABLE IF NOT EXISTS PROFESSORES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    NUMERO_FUNCIONARIO INT UNSIGNED NOT NULL,
    DEPARTAMENTO VARCHAR(255) NOT NULL,
    CONTACTO VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    LIVROS INT NOT NULL DEFAULT 0,
    PASS VARCHAR(255) NOT NULL DEFAULT '54321'
);

CREATE TABLE IF NOT EXISTS LIVROS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(255) NOT NULL,
    AUTOR VARCHAR(255) NOT NULL,
    ANO INT UNSIGNED NOT NULL,
    ISBN VARCHAR(255) NOT NULL,
    CATEGORIA VARCHAR(255) NOT NULL,
    NUMERO_COPIAS INT NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPRESTIMOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ALUNO_ID INT DEFAULT NULL,
    PROFESSOR_ID INT DEFAULT NULL,
    LIVRO_ID INT NOT NULL,
    DATA_ENTRADA DATE NOT NULL,
    DATA_SAIDA DATE NOT NULL,
    FOREIGN KEY(ALUNO_ID) REFERENCES ESTUDANTES(ID),
    FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSORES(ID)
);

ALTER TABLE EMPRESTIMOS
MODIFY COLUMN DATA_SAIDA DATE;

INSERT INTO LIVROS (TITULO, AUTOR, ANO, ISBN, CATEGORIA, NUMERO_COPIAS) VALUES
('Clean Code', 'Robert C. Martin', 2008, '9780132350884', 'Programming', 5),
('The Pragmatic Programmer', 'Andrew Hunt', 1999, '9780201616224', 'Programming', 3),
('Introduction to Algorithms', 'Thomas H. Cormen', 2009, '9780262033848', 'Programming', 4),
('Design Patterns', 'Erich Gamma', 1994, '9780201633610', 'Programming', 2),
('You Don’t Know JS', 'Kyle Simpson', 2014, '9781491904244', 'Programming', 6);

INSERT INTO ESTUDANTES (NOME, NUMERO_ESTUDANTE, CURSO, CONTACTO, EMAIL, LIVROS) VALUES
('Marcos', 12345, 'Engenharia Informatica', '5833119', 'maky188pgt555@gmail.com', 0),
('Leonardo', 12346, 'Engenharia Informatica', '9970507', 'lf714422@gmail.com', 0),
('Jose', 12347, 'Engenharia Informatica', '5805315', 'jose@gay.com', 0);

INSERT INTO PROFESSORES (NOME, NUMERO_FUNCIONARIO, DEPARTAMENTO, CONTACTO, EMAIL, LIVROS) VALUES
('Emmanuel', 54321, 'Computer Science', '987-654-3210', 'emmanuel@mestre.com', 0),
('Joao', 54322, 'Information Systems', '987-654-3211', 'joao@leiohm.com', 0),
('Elisangela', 54323, 'Software Engineering', '987-654-3212', 'elisangela@matematica.com', 0);

DELIMITER //

CREATE TRIGGER before_insert_emprestimos
BEFORE INSERT ON EMPRESTIMOS
FOR EACH ROW
BEGIN
    DECLARE user_type VARCHAR(255);
    
    SELECT 'ESTUDANTE' INTO user_type
    FROM ESTUDANTES
    WHERE ID = NEW.ALUNO_ID;
    
    IF user_type IS NOT NULL THEN
        SET NEW.DATA_SAIDA = DATE_ADD(NEW.DATA_ENTRADA, INTERVAL 15 DAY);
    ELSE
        SELECT 'PROFESSOR' INTO user_type
        FROM PROFESSORES
        WHERE ID = NEW.PROFESSOR_ID;
        
        IF user_type IS NOT NULL THEN
            SET NEW.DATA_SAIDA = DATE_ADD(NEW.DATA_ENTRADA, INTERVAL 30 DAY);
        END IF;
    END IF;
END;

//

DELIMITER ;

